// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v2

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// ClusterResourceQuotaSpecApplyConfiguration represents an declarative configuration of the ClusterResourceQuotaSpec type for use
// with apply.
type ClusterResourceQuotaSpecApplyConfiguration struct {
	Quota             *QuotaApplyConfiguration            `json:"quota,omitempty"`
	NamespaceSelector *v1.LabelSelectorApplyConfiguration `json:"namespaceSelector,omitempty"`
}

// ClusterResourceQuotaSpecApplyConfiguration constructs an declarative configuration of the ClusterResourceQuotaSpec type for use with
// apply.
func ClusterResourceQuotaSpec() *ClusterResourceQuotaSpecApplyConfiguration {
	return &ClusterResourceQuotaSpecApplyConfiguration{}
}

// WithQuota sets the Quota field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Quota field is set to the value of the last call.
func (b *ClusterResourceQuotaSpecApplyConfiguration) WithQuota(value *QuotaApplyConfiguration) *ClusterResourceQuotaSpecApplyConfiguration {
	b.Quota = value
	return b
}

// WithNamespaceSelector sets the NamespaceSelector field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NamespaceSelector field is set to the value of the last call.
func (b *ClusterResourceQuotaSpecApplyConfiguration) WithNamespaceSelector(value *v1.LabelSelectorApplyConfiguration) *ClusterResourceQuotaSpecApplyConfiguration {
	b.NamespaceSelector = value
	return b
}
