// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v2

import (
	v1 "k8s.io/api/core/v1"
)

// ClusterResourceQuotaStatusApplyConfiguration represents an declarative configuration of the ClusterResourceQuotaStatus type for use
// with apply.
type ClusterResourceQuotaStatusApplyConfiguration struct {
	Hard *v1.ResourceList `json:"hard,omitempty"`
	Used *v1.ResourceList `json:"used,omitempty"`
}

// ClusterResourceQuotaStatusApplyConfiguration constructs an declarative configuration of the ClusterResourceQuotaStatus type for use with
// apply.
func ClusterResourceQuotaStatus() *ClusterResourceQuotaStatusApplyConfiguration {
	return &ClusterResourceQuotaStatusApplyConfiguration{}
}

// WithHard sets the Hard field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Hard field is set to the value of the last call.
func (b *ClusterResourceQuotaStatusApplyConfiguration) WithHard(value v1.ResourceList) *ClusterResourceQuotaStatusApplyConfiguration {
	b.Hard = &value
	return b
}

// WithUsed sets the Used field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Used field is set to the value of the last call.
func (b *ClusterResourceQuotaStatusApplyConfiguration) WithUsed(value v1.ResourceList) *ClusterResourceQuotaStatusApplyConfiguration {
	b.Used = &value
	return b
}
