// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v2

import (
	v1 "k8s.io/api/core/v1"
)

// QuotaApplyConfiguration represents an declarative configuration of the Quota type for use
// with apply.
type QuotaApplyConfiguration struct {
	Hard *v1.ResourceList `json:"hard,omitempty"`
}

// QuotaApplyConfiguration constructs an declarative configuration of the Quota type for use with
// apply.
func Quota() *QuotaApplyConfiguration {
	return &QuotaApplyConfiguration{}
}

// WithHard sets the Hard field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Hard field is set to the value of the last call.
func (b *QuotaApplyConfiguration) WithHard(value v1.ResourceList) *QuotaApplyConfiguration {
	b.Hard = &value
	return b
}
