---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - resourcequotas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - accurate.cybozu.com
  resources:
  - clusterresourcequotas
  - subnamespaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - accurate.cybozu.com
  resources:
  - clusterresourcequotas/finalizers
  - subnamespaces/finalizers
  verbs:
  - update
- apiGroups:
  - accurate.cybozu.com
  resources:
  - clusterresourcequotas/status
  - subnamespaces/status
  verbs:
  - get
  - patch
  - update
