apiVersion: v1
kind: Pod
metadata:
  namespace: frontend-sub-1
  name: frontend-sub-1
spec:
  containers:
  - image: busybox
    name: buxybox
    resources:
      limits:
        memory: 30Mi
---
apiVersion: v1
kind: Pod
metadata:
  namespace: frontend-sub-2
  name: frontend-sub-2
spec:
  containers:
  - image: busybox
    name: buxybox
    resources:
      limits:
        memory: 30Mi
---
apiVersion: v1
kind: Pod
metadata:
  namespace: frontend-sub-3
  name: frontend-sub-3
spec:
  containers:
  - image: busybox
    name: buxybox
    resources:
      limits:
        memory: 30Mi
